---
- name: Install kiosk packages
  ansible.builtin.apt:
    name:
      - cifs-utils
      - chromium-browser
      - curl
      - nodejs
      - npm
      - rsync
      - smbclient
      - unclutter
      - xdotool
    state: present
    update_cache: true
