---
- name: Install kiosk packages
  ansible.builtin.apt:
    name:
      - cifs-utils
      - chromium-browser
      - nodejs
      - npm
      - rsync
      - smbclient
      - unclutter
    state: present
    update_cache: true
